-- MySQL Script generated by MySQL Workbench
-- Fri Mar 23 17:28:33 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`prisoner_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prisoner_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NULL,
  `last_name` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(1000) NULL,
  `term_sentence` INT NULL,
  `prison_name` VARCHAR(1000) NULL,
  `prisoner_number` INT NULL,
  `birth_date` DATE NULL,
  `sentence_start_date` DATE NULL,
  `rating` INT NULL,
  `registration_status` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`qualification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`qualification` (
  `id` INT NOT NULL,
  `prisoner_id` INT NULL,
  `education_level` INT NULL,
  `institution` VARCHAR(1000) NULL,
  `cv_link` VARCHAR(1000) NULL,
  INDEX `id_idx` (`prisoner_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `id`
    FOREIGN KEY (`prisoner_id`)
    REFERENCES `mydb`.`prisoner_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
